#!/bin/bash

echo "mydir"
echo cd /home/lumingqi/package
echo cd /home/lumingqi/server
echo cd /home/lumingqi/local

echo "sysdir"
echo cd /app
echo cd /usr/local

echo "global"
echo cd /etc/init.d
echo vi /etc/profile
echo source /etc/profile
